export enum SwitchShorts {
  'akko cs jelly pink' = 'AJP',
  'akko cs jelly purple' = 'AJR',
  'cherry mx black' = 'CBL',
  'cherry mx rgb black' = 'CBL',
  'cherry mx blue' = 'CB',
  'cherry mx rgb blue' = 'CB',
  'cherry mx brown' = 'CBR',
  'cherry mx rgb brown' = 'CBR',
  'cherry mx clear' = 'CCL',
  'cherry mx rgb clear' = 'CCL',
  'cherry mx silent red' = 'CSR',
  'cherry mx rgb silent red' = 'CSR',
  'cherry mx speed silver' = 'CSS',
  'cherry mx rgb speed silver' = 'CSS',
  'cherry mx red' = 'R',
  'cherry mx rgb' = 'R',
  'cherry mx rgb red' = 'R',
  'cherry mx silent black' = 'SB',
  'cherry mx green' = 'GR',
  'gateron cap v2 crystal brown' = 'CRBR',
  'gateron cap v2 crystal blue' = 'CRB',
  'gateron cap v2 crystal red' = 'CRR',
  'gateron cap v2 crystal yellow' = 'CRY',
  'gateron cap v2 crystal silent red' = 'CRSR',
  'gateron cap v2 crystal speed silver' = 'CRSS',
  'gateron g pro red' = 'PR',
  'gateron g pro brown' = 'PBR',
  'gateron g pro blue' = 'PB',
  'gateron g pro 2 silver' = 'PS2',
  'gateron g pro 2 white' = 'PW2',
  'gateron g pro 2 yellow' = 'PY2',
  'gateron g pro 2 red' = 'PR2',
  'gateron g pro 2 brown' = 'BR2',
  'gateron g pro yellow' = 'PY',
  'gateron low profile blue' = 'LB',
  'gateron low profile brown' = 'LBR',
  'gateron low profile red' = 'LR',
  'kailh prestige red' = 'KPR',
  'kailh prestige clicky' = 'KPC',
  'keychron optical low profile brown' = 'KBR',
  'keychron optical low profile red' = 'KLR',
  'keychron optical low profile mint' = 'KLM',
  'keychron optical low profile banana' = 'KLN',
  'keychron optical low profile blue' = 'KLB',
  'novelkeys x kailh box crystal navy' = 'NA',
  'novelkeys x kailh box crystal royal' = 'KRO',
  'topre 45g' = 'T4',
  'topre 45g silent' = 'T4S',
  'topre 30g' = 'T3',
  'topre variable' = 'TV',
  'topre variable silent' = 'TVS',
  'ttc speed silver' = 'TSS',
  'varmilo ec v2 jasmine' = 'EJ',
  'varmilo ec v2 iris' = 'EIR',
  'varmilo ec v2 violet' = 'EV',
  'varmilo ec daisy v2' = 'ED',
  'varmilo ec sakura v2' = 'ES',
  'varmilo ec rose v2' = 'ER',
  'varmilo ec ivy v2' = 'EI',
  'zeal pc tealios v2' = 'TE',
  'zeal pc zilents v2 67g' = 'ZI',
  'zeal pc zealios v2 67g' = 'ZE',
}

export enum FilterCategory {
  available,
  manufacturer,
  switches,
  minPrice,
  maxPrice,
  minQuantity,
  maxQuantity,
  brand,
  size,
  features,
  search,
}
